#!/bin/bash

## Reset various config files

# Test command parameters
compile=1
resartserv=1
clearcahes=1
buildassests=1
migrate=1
showhelp=0
installpath="openeyes"
confpath=""
custompath=0
customconfpath=0
migrateparams=""

for i in "$@"
do
case $i in
	--no-compile) compile=0
	;;
	--no-restart) resartserv=0
	;;
	--no-clear) clearcahes=0
	;;
	--no-assets) buildassests=0
	;;
    --no-migrate|--nomigrate) migrate=0
	;;
    --help) showhelp=1
    ;;
	--path) custompath=1; migrateparams="$migrateparams $i"
    ;;
    --conf-path) customconfpath=1; migrateparams="$migrateparams $i"
    ;;
	*)  if [ ! -z "$i" ]; then
			if [ $custompath = 1 ]; then
                installpath=$i
                custompath=0
				migrateparams="$migrateparams $i"
            elif [ $customconfpath = 1 ]; then
                confpath=$i
                customconfpath=0
				migrateparams="$migrateparams $i"
			else echo "Unknown command line: $i"
				## Set branch name
			fi
		fi
    ;;
esac
done

# Show help text
if [ $showhelp = 1 ]; then
    echo ""
    echo "DESCRIPTION:"
    echo "Applies various fixes to make sure files in in the correct place, database is migrated, code is compiled, etc."
    echo ""
    echo "usage: $0 <branch> [--help] [--no-compile] [--no-restart] [--no-clear ] [--no-assets] [--no-migrate]"
    echo ""
    echo "COMMAND OPTIONS:"
	echo ""
	echo "  --help         : Show this help"
    echo "  --no-compile   : Do not complile java modules"
	echo "  --no-restart   : Do not restart services"
	echo "  --no-clear     : Do not clear caches"
	echo "  --no-assets    : Do not (re)build assets"
    echo "  --no-migrate   : Do not run db migrations"
	echo ""
    exit 1
fi

# If custom path has been set, but no custom configpath/dbmane then assume config path and db name will be same as custom install path name
if [ -z $confpath ]; then
    confpath=$installpath
fi

source /etc/$confpath/env.conf

cd /var/www/$installpath
if [ -f ".htaccess.sample" ]; then
echo Renaming .htaccess file
mv .htaccess.sample .htaccess
if [ ! "$env" = "VAGRANT" ]; then chown -R www-data:www-data .htaccess; fi
fi

if [ -f "index.example.php" ]; then
echo Renaming index.php file
mv index.example.php index.php
if [ ! "$env" = "VAGRANT" ]; then chown -R www-data:www-data index.php; fi
fi

if [ ! -d "protected/config/local" ]; then
	echo "WARNING: this code branch uses db settings from common.php, not /etc/$confpath"
	mv protected/config/local.sample protected/config/local
	mv protected/config/local/common.sample.php protected/config/local/common.php
	if [ ! "$envtype" = "VAGRANT" ]; then chown -R www-data:www-data protected/config/local; fi
	chmod -R 775 protected/config/local
	# When using old oe versions, overwirte password in commpon.php to use new default usermname/password
	sed -i "s/'username' => 'root',/'username' => 'openeyes',/" /var/www/$installpath/protected/config/local/common.php
	sed -i "s/'password' => '',/'password' => 'openeyes',/" /var/www/$installpath/protected/config/local/common.php
fi;

# Make sure yii framework found/linked
rm "/var/www/$installpath/vendor/yiisoft/yii" 2>/dev/null || :
mkdir -p /var/www/$installpath/vendor/yiisoft
if [ ! "$envtype" = "VAGRANT" ]; then chown -R www-data:www-data /var/www/$installpath/vendor; fi

if [ -d "/usr/lib/openeyes/yii" ]; then
	# v1.12+
	echo "Linking Yii framework to /usr/lib/openeyes/yii"
	ln -s /usr/lib/openeyes/yii /var/www/$installpath/vendor/yiisoft/yii
else
	#fix for pre v1.12
	echo "Linking Yii framework to /var/www/$installpath/protected/yii"
	ln -s /var/www/$installpath/protected/yii /var/www/$installpath/vendor/yiisoft/yii
fi


# Make sure vendor directory found/linked
if [ ! -d "/var/www/$installpath/protected/vendors" ]; then
	echo Linking vendor framework
	ln -s /usr/lib/openeyes/vendors /var/www/$installpath/protected/vendors
	chown -R www-data:www-data /var/www/$installpath/protected/vendors 2>/dev/null || :
	if [ ! $? = 0 ]; then echo "unable to link vendors - this is expected for versions prior to v1.12"; fi
fi

## (re)-link dist directory for IOLMasterImport module and recompile
dwservrunning=0
# first check if service is running - if it is we stop it, then re-start at the end
if ps ax | grep -v grep | grep run-dicom-service.sh > /dev/null
	then
		dwservrunning=1
		echo "Stopping dicom-file-watcher..."
		service dicom-file-watcher stop
fi

cd /var/www/$installpath/protected/javamodules/IOLMasterImport
rm -rf dist/lib 2>/dev/null || :
mkdir -p dist
ln -s ../lib ./dist/lib
if [ ! $? = 0 ]; then echo "Failure is expeced in pre v1.12 releases (where IOLMasterImport does not exist)"; fi

# Compile IOLImporter
##TODO: When we have more java modules, replace with a generic compilation model
if [ $compile = 1 ]; then
  echo "
  Compiling IOLMAsterImport. Please wait....
  "
  ./compile.sh > /dev/null 2>&1
  if [ ! $? = 0 ]; then echo "Failure is expeced in pre v1.12 releases (where IOLMasterImport does not exist)"; fi
fi

# restart the service if we stopped it
if [ $dwservrunning = 1 ] && [ $resartserv = 1 ]; then
	echo "Restarting dicom-file-watcher..."
	service dicom-file-watcher start
fi

# Automatically migrate up, unless --no-migrate parameter is given
if [ "$migrate" = "1" ]; then
    echo ""
    echo "Migrating database..."
	oe-migrate --quiet $migrateparams
    echo ""
else
	echo "
Migrations were not run automaically. If you need to run the database migrations, run command oe-migrate
"
fi

# Clear caches
if [ $clearcahes = 1 ]; then
	echo "Clearing caches..."
	rm -rf /var/www/$installpath/protected/runtime/cache/* 2>/dev/null || :
	rm -rf /var/www/$installpath/assets/* 2>/dev/null || :
	echo ""
fi

if [ $buildassests = 1 ]; then
	echo "(re)building assets..."
	# use curl to ping the login page - forces php/apache to rebuild the assets directory
	curl -s http://localhost/site/login > /dev/null
fi

echo ""
echo "...Done"
echo ""
