#!/bin/bash

## Process command parameters
quiet=0
showhelp=0
installpath="openeyes"
confpath=""
custompath=0
customconfpath=0

for i in "$@"
do
case $i in
	--quiet|-q) quiet=1
	;;
    --help) showhelp=1
    ;;
	--path) custompath=1
	;;
	--conf-path) customconfpath=1
    ;;
	*)  if [ ! -z "$i" ]; then
			if [ $custompath = 1 ]; then
                installpath=$i
                custompath=0
            elif [ $customconfpath = 1 ]; then
                confpath=$i
                customconfpath=0
			else echo "Unknown command line: $i"
				## Set branch name
			fi
		fi
    ;;
esac
done

# Show help text
if [ $showhelp = 1 ]; then
    echo ""
    echo "DESCRIPTION:"
    echo "Migrates database to latest schema"
    echo ""
    echo "usage: $0 [--help] [--quiet | -q]"
    echo ""
    echo "COMMAND OPTIONS:"
	echo ""
	echo "  --help         : Show this help"
    echo "  --quiet | -q   : Do not show console output"
	echo ""
    exit 1
fi

# If custom path has been set, but no custom configpath/dbmane then assume config path and db name will be same as custom install path name
if [ -z $confpath ]; then
    confpath=$installpath
fi

dir=$PWD
cd /var/www/$installpath/protected
if [ $quiet = 0 ]; then
    ./yiic migrate --interactive=0
    ./yiic migratemodules --interactive=0
else
    ./yiic migrate --interactive=0 > /etc/$confpath/migrate.log
    ./yiic migratemodules --interactive=0 >> /etc/$confpath/migrate.log
    echo "Migrations applied - see /etc/$confpath/migrate.log for more details"
fi
cd "$dir"
